on: [workflow_dispatch]

jobs:
  hello_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses:  LuckMk1-evil-organization/action-test/composite@v1
        with:
          Who: 'Le monde !'
